routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::middleware('example-saml-auth')->group(function () {
//     Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');
// });
// Route::redirect('about-page', 'about');

Route::middleware('example-saml-auth')->group(function () {
    Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');

});

Route::namespace('Auth')->group(function () {
    Route::post('login', 'LoginController@authenticate')->name('login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    // Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');
});

    Route::group(['middleware' => 'App\Http\Middleware\Authenticate'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/dashboardUser', 'DashboardUserController@index')->name('dashboardUser');
    Route::get('/dashboardShow-{id}', 'DashboardUserController@show')->name('dashboardShow');

    //Route::get('/dashboardUser-{id}', 'dashboardUserController@show')->name('dashboard');
    Route::get('file/download/{file}', 'kumpulanEbookController@download')->name('download');
    Route::resource('/user', 'UserController');
    Route::get('/profil', 'ProfilController@index')->name('profil.index');
    Route::post('/update-profil/{id}', 'ProfilController@update')->name('update.profil');
    Route::match(['get', 'post'], '/edit/{id}', 'KategoriController@edit');
    //Route::match(['get', 'post'], '/edit/{id}', 'sliderController@edit');
    Route::resource('/document', 'KelolaDocumentController');
    Route::get('/delete/{id}', 'KelolaDocumentController@delete')->name('delete');
    Route::get('/hapus/{id}', 'DocumentController@hapus')->name('hapus');
    Route::get('/buang/{id}', 'KategoriController@buang')->name('buang');
    Route::get('/komen/{id}', 'ForumController@komen')->name('komen');
    Route::get('/buku/{id}', 'AdminEbookController@buku')->name('buku');
    Route::get('/bukuadmin/{id}', 'EbookController@bukuadmin')->name('bukuadmin');
    Route::get('/usersdel/{id}', 'UserController@usersdel')->name('usersdel');
    Route::resource('/doc', 'DocumentController');
    Route::resource('/kategori', 'KategoriController')->except(['destroy']);;
    Route::resource('/like', 'MyLikeController');
    Route::resource('/reference', 'MyReferenceController');
    Route::resource('/forum', 'ForumController');
    Route::resource('/ebook', 'EbookController');
    Route::resource('/adminEbook', 'AdminEbookController');
    Route::resource('/kumpulanEbook', 'KumpulanEbookController');
    Route::post('/documen/{id}', 'MyReferenceController@komentar');
    Route::get('report', 'KelolaDocumentController@report')->name('report');
    Route::get('reportAdmin', 'DocumentController@report')->name('reportAdmin');
    Route::get('reportcomen', 'ForumController@reportc')->name('reportcomen');
    Route::get('export', 'UserController@export')->name('export');
    Route::get('kategoriexport', 'KategoriController@reportkategori')->name('kategoriexport');
    Route::post('import', 'UserController@importexel')->name('import');
    Route::post('importdokumen', 'UserController@importexel')->name('importdokumen');
    Route::post('importkategori', 'KategoriController@import')->name('importkategori');
    Route::post('/likedislike', 'KategoriController@likedislike')->name('likedislike');
    Route::post('/viewadd', 'MyReferenceController@addview')->name('viewadd');
    Route::post('/filter', 'KategoriController@filter')->name('filter');
    Route::get('/preview-{id}', 'PreviewController@index')->name('preview');
    Route::get('/previewdoc-{id}', 'PreviewdocController@index')->name('previewdoc');
    Route::post('/getjudul', 'MyReferenceController@getjudul');
    Route::post('/reference/{id}', 'MyReferenceController@insertData')->name('reference.insertData');
    Route::resource('/gambar', 'GambarController');
    Route::get('locale/{locale}', function ($locale) {
        \Session::put('locale', $locale);
        return redirect()->back();
    });
    });
Route::view('loginn', 'general.loginn');
    // Route::get('/', function () {
    // if( Auth::check() && Auth::user()->hasRole("pusdiklat") ) {
    //             return redirect()->intended('dashboard');
    // }
    // else {
    // return redirect()->intended('dashboardUser');
    // }
    // })->name('home');

// Route::get('/', function () {
//         return redirect('dahsboardUuser');
//     });

// Route::get('/', function () {
//     return view('general.loginn');
// })->name('home');

    

Route::get('/', function () {
    return view('general.loginn');
})->name('home');


// Route::get('/', function () {
//     return redirect('ReferenceLearning');
// })->name('home');;

// Route::view('ReferenceLearning', 'general.login');

// Route::get('/ReferenceLearning', 'LoginController@index')->name('general.login');

app/Http/Controllers/KumpulanEbookController.php
<?php

namespace App\Http\Controllers;



use Illuminate\Http\Request;
use App\Models\Ebook;
use App\Models\kategori;
use App\Models\status;
use Illuminate\Support\Facades\Storage;

class KumpulanEbookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        
        $this->middleware('permission:kumpulan-buku', ['only' => ['index', 'show']]);
    }

    public function index(Request $request)
    {

        $status = Status::rejected()->first();
        // dd($status);
        // $nama_status = '';
        $filterKeyword = $request->get('keyword');
        $kumpulan = Ebook::orderBy('created_at', 'desc')->where('id_status', $status->id_status)->paginate(10);
        if ($filterKeyword) {
            //dijalankan jika ada pencarian
            $kumpulan = Ebook::where('judul_ebook', 'LIKE', "%$filterKeyword%")->paginate(10);
        }
        return view('kumpulanEbook.index', compact('kumpulan'));
    }

    public function download($file)
    {
        return response()->download('/storage/' . $file); //Download file yang dicari berdasarkan nama file
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/kumpulanEbook/show.blade.php
@extends('layoutt.master-template')

@section('titlel')
<a href="{{route('reference.index')}}"> Reference </a> /  Baca dokument
@endsection

@section('content')



<div class="row mt-2">
    <div class="col-md-12">

        <div class="list-group">

            <div class=" card list-group-item">
                <a href="{{route('reference.index')}}" class="btn btn-info btn-xl">Kembali</a>
              <hr>
                <div class="row">
                    <div class="container" >
                        <div class="col-md-12">
                        {{-- @foreach ($reference as $item) --}}
                            <label for="file" class="col-sm-2 control-label"></label>
                            <div class="embed-responsive embed-responsive-4by3">
                                <iframe class="embed-responsive-item" type="application / html5"
                                    src="{{ asset('uploads/'.$reference->file) }}#toolbar=0&navpanes=0&scrollbar=0" 
                                    width="100%" height="1000"></iframe>
                            </div>
                        </div>
                        <div class="col-md-4">
                            
                        </div>
                    </div>
                    <div class="col px-4">
                        <br>
                        <div>
                            {{-- @foreach ($reference as $id)
                            <h4 class="media-heading">{{ $id->judul_dokumen }}</h4>
                            <p>{{$id->deskripsi_dokumen}}</p>
                            @endforeach --}}
                            <a href="javascript:void(0)">
                                <i class="fas fa-thumbs-up tekan"></i> {{$reference->jumlah_like}}
                            </a>
                            <a href="javascript:void(0)"> |
                                <i class="far fa-eye"></i> {{$reference->jumlah_view}}
                            </a>
                            <a class="tahun" style="color : #aaa !important;" href=""> | Create : {{$reference->tahun}}</a>
                            <div class="float-right">
                                    <h5 id="id_kategori" name="id_kategori">Kategori : {{$reference->kategori->kategori}} </h5>
                            </div>
                        </div>
                        <br>
                        <hr>
                      
                        {{-- @if($reference->id_forum == $komentar->id) --}}
            <div class="card direct-chat direct-chat-primary">
              <div class="card-header ui-sortable-handle" style="cursor: move;">
                <h2 class="card-title">Komentar</h2>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <!-- Conversations are loaded here -->
                       <div class="direct-chat-messages">
                                    <!-- Message. Default to the left -->
                            @foreach ($komentar as $item)
                            {{-- @if($item->documen_id == $komentar) --}}
                                <form method="post" action="{{ route('reference.destroy',[$item->id]) }}"
                                            onsubmit="return confirm('Apakah anda yakin akan menghapus komentar ini ?')">
                                            @csrf
                                            {{ method_field('DELETE') }} 
                                    <div class="direct-chat-msg">
                                        <div class="direct-chat-infos clearfix" id="comment_{{ $item->id }}">
                                                <span class="direct-chat-name float-left">{{$item->user->full_name}}</span>
                                                @if($item->user->full_name == Auth::user()->full_name)
                                                <span class="direct-chat-name"><button type="submit" class="btn btn-tool" data-card-widget=""><i class="fas fa-times"></i>
                                                </button></span>
                                                @endif
                                                <span class="direct-chat-timestamp float-right">{{$item->created_at}}</span>
                                        </div>
                                        <div class="direct-chat-text" >
                                                {{$item->message}}
                                        </div>
                                            <!-- /.direct-chat-text -->
                                    </div>
                                </form>
                                {{-- @endif --}}
                            @endforeach
                        </div>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <form method="post" action="{{route('reference.store')}}"id="comment_{{ $item->id }} class="form-horizontal">
                               @csrf  
                               <input  type="hidden" name="_name" value="<?php echo csrf_token()?>">
                  <div class="input-group">
                   <textarea type="text" name="message" placeholder="Type Message ..." class="form-control" cols="10" rows="3" required></textarea>
                  </div>
                      <button data-id="{{ $item->id }}" data-token="{{ csrf_token() }}" style="margin-top: 5px"type="submit" class="btn btn-primary " value="Komentar">Komentar <i class="fas fa-paper-plane"></i> </button>
                              </form>
              </div>
              <!-- /.card-footer-->
            </div>
                        {{-- @endif --}}
                </div>

            </div>
        </div>
    </div>
</div>

<script>
    $(".commentButton").click(function(){
    var id = $(this).data("id");
    var comment = $("input[name=comment]").val();
    var token = $(this).data("token");

    $.ajax({
       url: "/comments/"+id,
       type: 'POST',
       dataType: 'JSON',
       data: {
           "id": id,
           "message": message,
           "_method": 'POST',
           "_token": token,
       },
       success: function(){
           console.log('it works!');
            $(".direct-chat-messages").html(data.komentar);
       } 
    });
    console.log("It failed"); 
});
// $('#comment_'+id);
</script>
@endsection