routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::middleware('example-saml-auth')->group(function () {
//     Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');
// });
// Route::redirect('about-page', 'about');

Route::middleware('example-saml-auth')->group(function () {
    Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');

});

Route::namespace('Auth')->group(function () {
    Route::post('login', 'LoginController@authenticate')->name('login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    // Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');
});

    Route::group(['middleware' => 'App\Http\Middleware\Authenticate'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/dashboardUser', 'DashboardUserController@index')->name('dashboardUser');
    Route::get('/dashboardShow-{id}', 'DashboardUserController@show')->name('dashboardShow');

    //Route::get('/dashboardUser-{id}', 'dashboardUserController@show')->name('dashboard');
    Route::get('file/download/{file}', 'kumpulanEbookController@download')->name('download');
    Route::resource('/user', 'UserController');
    Route::get('/profil', 'ProfilController@index')->name('profil.index');
    Route::post('/update-profil/{id}', 'ProfilController@update')->name('update.profil');
    Route::match(['get', 'post'], '/edit/{id}', 'KategoriController@edit');
    //Route::match(['get', 'post'], '/edit/{id}', 'sliderController@edit');
    Route::resource('/document', 'KelolaDocumentController');
    Route::get('/delete/{id}', 'KelolaDocumentController@delete')->name('delete');
    Route::get('/hapus/{id}', 'DocumentController@hapus')->name('hapus');
    Route::get('/buang/{id}', 'KategoriController@buang')->name('buang');
    Route::get('/komen/{id}', 'ForumController@komen')->name('komen');
    Route::get('/buku/{id}', 'AdminEbookController@buku')->name('buku');
    Route::get('/bukuadmin/{id}', 'EbookController@bukuadmin')->name('bukuadmin');
    Route::get('/usersdel/{id}', 'UserController@usersdel')->name('usersdel');
    Route::resource('/doc', 'DocumentController');
    Route::resource('/kategori', 'KategoriController')->except(['destroy']);;
    Route::resource('/like', 'MyLikeController');
    Route::resource('/reference', 'MyReferenceController');
    Route::resource('/forum', 'ForumController');
    Route::resource('/ebook', 'EbookController');
    Route::resource('/adminEbook', 'AdminEbookController');
    Route::resource('/kumpulanEbook', 'KumpulanEbookController');
    Route::post('/documen/{id}', 'MyReferenceController@komentar');
    Route::get('report', 'KelolaDocumentController@report')->name('report');
    Route::get('reportAdmin', 'DocumentController@report')->name('reportAdmin');
    Route::get('reportcomen', 'ForumController@reportc')->name('reportcomen');
    Route::get('export', 'UserController@export')->name('export');
    Route::get('kategoriexport', 'KategoriController@reportkategori')->name('kategoriexport');
    Route::post('import', 'UserController@importexel')->name('import');
    Route::post('importdokumen', 'UserController@importexel')->name('importdokumen');
    Route::post('importkategori', 'KategoriController@import')->name('importkategori');
    Route::post('/likedislike', 'KategoriController@likedislike')->name('likedislike');
    Route::post('/viewadd', 'MyReferenceController@addview')->name('viewadd');
    Route::post('/filter', 'KategoriController@filter')->name('filter');
    Route::get('/preview-{id}', 'PreviewController@index')->name('preview');
    Route::get('/previewdoc-{id}', 'PreviewdocController@index')->name('previewdoc');
    Route::post('/getjudul', 'MyReferenceController@getjudul');
    Route::post('/reference/{id}', 'MyReferenceController@insertData')->name('reference.insertData');
    Route::resource('/gambar', 'GambarController');
    Route::get('locale/{locale}', function ($locale) {
        \Session::put('locale', $locale);
        return redirect()->back();
    });
    });
Route::view('loginn', 'general.loginn');
    // Route::get('/', function () {
    // if( Auth::check() && Auth::user()->hasRole("pusdiklat") ) {
    //             return redirect()->intended('dashboard');
    // }
    // else {
    // return redirect()->intended('dashboardUser');
    // }
    // })->name('home');

// Route::get('/', function () {
//         return redirect('dahsboardUuser');
//     });

// Route::get('/', function () {
//     return view('general.loginn');
// })->name('home');

    

Route::get('/', function () {
    return view('general.loginn');
})->name('home');


// Route::get('/', function () {
//     return redirect('ReferenceLearning');
// })->name('home');;

// Route::view('ReferenceLearning', 'general.login');

// Route::get('/ReferenceLearning', 'LoginController@index')->name('general.login');

resources/views/doc/create.blade.php
@extends('layoutt.master-template')

@section('title')
Input Documen
@endsection

@section('content')

<div class="col-md-12">
    <!-- general form elements disabled -->
    <!-- /.card-header -->
    <div class="card-body">
      
        <form method="post" action="{{ route('doc.store')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="judul_dokumen">judul</label>
                <input name="judul_dokumen" id="judul_dokumen" class="form-control @error('judul_dokumen') is-invalid @enderror" placeholder="apa judulnya"
                    value="{{old('judul_dokumen')}}">
                    @error('judul_dokumen')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="id_kategori">Kategori</label>
                        <select id="id_kategori" name="id_kategori" class="form-control @error('id_kategori') is-invalid @enderror">
                           <option selected disabled style="font-weight: bold;">Teknis : </option>
                            @foreach($kategori as $row )
                            @if($row->kategori_type_id == 1)
                            <option value="{{ $row->id_kategori }}">{{ $row->kategori }} </option>
                            @endif
                            @endforeach
                            <option selected disabled style="font-weight: bold;"> Non Teknis : </option>
                            @foreach($kategori as $row )
                            @if($row->kategori_type_id == 2)
                            <option value="{{ $row->id_kategori }}">{{ $row->kategori }}</option>
                            @endif
                            @endforeach
                            <option selected disabled>Kategori</option>
                        </select>
                        @error('id_kategori')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                    <!-- text input -->
                </div>
                <div class="col-sm-6">
                    <!-- text input -->
                    <div class="form-group ">
                        <label for="publisher">Penulis</label>
                        <input name="publisher" value="{{old('publisher')}}" id="publisher" class="form-control @error('publisher') is-invalid @enderror""
                            placeholder="siapa penulisanya" >
                           @error('publisher')
                            <div class="invalid-feedback">{{$message}}</div>
                            @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <!-- text input -->
                    <div class="form-group ">
                        <label for="tahun">Tahun Dibuat</label>
                        <input name="tahun" id="tahun" class="form-control @error('tahun') is-invalid @enderror" placeholder="berapa tahunnya"
                            value="{{old('tahun')}}">
                            @error('tahun')
                            <div class="invalid-feedback">{{$message}}</div>
                            @enderror
                    </div>

                </div>
                <div class="col-sm-6">
                    <!-- text input -->
                    <div class="form-group">
                        <label for="jumlah_halaman">jumlah halaman</label>
                        <input name="jumlah_halaman" id="jumlah_halaman" class="form-control @error('jumlah_halaman') is-invalid @enderror"
                            placeholder="berapa jumlahnya" value="{{old('jumlah_halaman')}}">
                            @error('jumlah_halaman')
                            <div class="invalid-feedback">{{$message}}</div>
                            @enderror
                    </div>

                </div>
            </div>
            <div class="form-group">
                <label for="deskripsi_dokumen">Deskripsi</label>
                <textarea name="deskripsi_dokumen"  value="{{old('deskripsi_dokumen')}}" class="form-control @error('deskripsi_dokumen') is-invalid @enderror" style="height: 600px;"></textarea>
                    @error('deskripsi_dokumen')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group @error('file') is-invalid @enderror">
                        <label for="file" class="col-sm-4 control-label">File document </label>
                        <p style="margin-top: -10px; margin-left:10px !important;">file zip max 50Mb</p>
                        <input value="{{old('file')}}" type="file" name="file" class="form-control @error('file') is-invalid @enderror">
                        @error('file')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group ">
                        <label for="cover" class="col-sm-4 control-label">Upload Gambar</label>
                        <p style="margin-top: -10px; margin-left:10px !important;">file png,jpg,jpeg max 5 Mb</p>
                        <input value="{{old('cover')}}" type="file" name="cover" class="form-control @error('cover') is-invalid @enderror" >
                        @error('cover')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>

            </div>

            <div class="form-group">
                <a href="{{route('doc.index')}}" class="btn btn-warning btn-xl"><span class="fas fa-backward"></span> Kembali</a>
                <button type="submit" class="btn btn-success btn-xl"><i class="far fa-save"></i> Simpan</button>

            </div>
        </form>

    </div>

</div>


@endsection

resources/views/doc/edit.blade.php
@extends('layoutt.master-template')

@section('title')
Edit Dokumen
@endsection

@section('content')
@push('addon-style')
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
@endpush
<div class="col-md-12">
    <!-- general form elements disabled -->
    <!-- /.card-header -->
    <div class="card-body">
        {{-- @if($errors->any())
        <ul class="alert alert-danger">
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
        @endif --}}
        
        <form class="form-horizontal" method="post" action="{{ route('doc.update',[$document->id]) }}" enctype="multipart/form-data">
            @csrf
            {{ method_field('PUT') }}
            <div class="form-group">
                <label for="judul_dokumen">judul</label>
                <input name="judul_dokumen" id="judul_dokumen" class="form-control @error('judul_dokumen') is-invalid @enderror" placeholder="apa judulnya"
                    value="{{$document->judul_dokumen}}">{{old('judul_dokumen')}}
                    @error('judul_dokumen')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="id_kategori">Kategori</label>
                        <select id="id_kategori" name="id_kategori" class="form-control @error('id_kategori') is-invalid @enderror">      
                           <option disabled style="font-weight: bold;">Teknis : </option>
                            @foreach($kategori as $row )
                            @if($row->kategori_type_id == 1)
                            <option value="{{ $row->id_kategori }}" @if($document->id_kategori == $row->id_kategori) Selected
                                @endif>{{ $row->kategori }}
                            </option>
                            @endif
                            @endforeach
                            <option disabled style="font-weight: bold;">Non Teknis : </option>
                            @foreach($kategori as $row )
                            @if($row->kategori_type_id == 2)
                            <option value="{{ $row->id_kategori }}" @if($document->id_kategori == $row->id_kategori) Selected
                                @endif>{{ $row->kategori }}
                            </option>
                            @endif
                            @endforeach
                        </select>
                        @error('id_kategori')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                    <!-- text input -->
                </div>
                <div class="col-sm-6">
                    <!-- text input -->
                    <div class="form-group">
                        <label for="publisher">Penulis</label>
                        <input name="publisher" value="{{$document->publisher}}" id="publisher" class="form-control @error('publisher') is-invalid @enderror"
                            placeholder="siapa penulisanya" value="">
                            @error('publisher')
                            <div class="invalid-feedback">{{$message}}</div>
                            @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <!-- text input -->
                    <div class="form-group ">
                        <label for="tahun">Tahun Dibuat</label>
                        <input name="tahun" id="tahun" class="form-control @error('tahun') is-invalid @enderror" placeholder="berapa tahunnya"
                            value="{{$document->tahun}}">
                            @error('tahun')
                            <div class="invalid-feedback">{{$message}}</div>
                            @enderror
                    </div>

                </div>
                <div class="col-sm-6">
                    <!-- text input -->
                    <div class="form-group ">
                        <label for="jumlah_halaman">jumlah halaman</label>
                        <input name="jumlah_halaman" id="jumlah_halaman" class="form-control @error('jumlah_halaman') is-invalid @enderror"
                            placeholder="berapa jumlahnya" value="{{$document->jumlah_halaman}}">
                            @error('jumlah_halaman')
                            <div class="invalid-feedback">{{$message}}</div>
                            @enderror
                    </div>

                </div>
            </div>
            <div class="form-group">
                <label for="deskripsi_dokumen">Deskripsi</label>
                <textarea name="deskripsi_dokumen"  class="form-control @error('deskripsi_dokumen') is-invalid @enderror" cols="30"
                    rows="10">{!!$document->deskripsi_dokumen!!}</textarea>
                    @error('deskripsi_dokumen')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
            </div>
            
  <hr>
                <label for="file" class="col-sm-2 control-label">File Dokumen</label>
                <div class="col-sm-12 embed-responsive embed-responsive-4by3">
                    <iframe class="embed-responsive-item" src="{{ asset('uploads/'.$document->file) }}"  width="100%">{{ asset('uploads/'.$document->file) }}</iframe>
                       
                </div>
            
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        {{-- <label for="file" class="col-sm-4 control-label">File document</label> --}}
                        <input type="file" name="file" class="form-control @error('file') is-invalid @enderror" id="file">
                        @error('file')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>

            </div>
            <hr>
                <label for="cover" class="col-sm-12 control-label">Cover Dokumen</label>
                <div class="col-sm-12 embed-responsive embed-responsive-4by3">

                    @if($document->cover)
                    <img class="embed-responsive-item" src="{{ asset('uploads/'.$document->cover) }}" class="img-thumbnail" width="80%" >
                    @else
                    <img class="embed-responsive-item" src="{{ asset('image/Picture1.png') }}" class="img-thumbnail" width="80%">
                    @endif
                </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        {{-- <label for="cover" class="col-sm-4 control-label">cover document</label> --}}
                        <input type="file" id="cover"name="cover" class="form-control @error('cover') is-invalid @enderror" id="cover">
                        @error('cover')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="form-group">
               <a href="{{route('doc.index')}}" class="btn btn-warning btn-xl"><span class="fas fa-backward"></span> Kembali</a>
                <button type="submit" name="tombol" class="btn btn-info pull-right">Update</button>
            </div>
        </form>

    </div>

</div>

@push('addon-script')
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
<script type="text/javascript">
    $('#summernote').summernote({
    tabsize: 2,
    height: 300
    });
</script>
@endpush
@endsection

resources/views/doc/index.blade.php
@extends('layoutt.master-template')

@section('title')
Document
@endsection

@section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">

                <div class="card">

                    <div class="card-header">
                        <h3 class="card-title">Kelola Document</h3>
                    </div>
                    <br />
                    <div class="col-md-10 offset-md-1 ">
                        @can("dokumen-create")
                        <a href="{{ route('doc.create') }}" class="btn btn-primary"><span
                                class=" fas fa-plus-square"></span>
                            Tambahkan Dokumen</a>
                        @endcan
                        @can("dokumen-export")
                        <a style="margin-left: 10px;" href="{{ route('reportAdmin') }}" class="btn btn-success"><i
                                class="far fa-file-excel"></i>
                            Export exel</a>
                        @endcan
                    </div>
                    {{-- <a href="{{route('user/export')}}" class="btn btn-success"><i class="far fa-file-excel"></i>
                    exel</a> --}}
                    <div class="modal fade" id="modal-default1">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Import</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <form method="post" action="{{route('importdokumen')}}" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group">
                                        <div class="modal-body">
                                            <label>Masukan Data</label>
                                            <input type="file" name="data_dokument" class="form-control"
                                                placeholder=" yuk masukan data" required>
                                        </div>
                                        <div class="modal-footer justify-content-between">
                                            <button type="button" class="btn btn-default"
                                                data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-success btn-xl"><i
                                                    class="far fa-save"></i> Simpan</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>

                    <br />

                    <div class="row">
                        <div class="col-md-10 offset-md-1">
                            <div class="row">
                                <div class="col-md-6">
                                    <form method="get" action="{{route('doc.index')}}">
                                        <div class="form-group">
                                            <label>Cari Kategori</label>
                                            <div class="input-group input-group-lg">
                                                <select id="id_kategori" name="id_kategori"
                                                    class="custom-select select2bs4" style="width: 50%;">
                                                    <option selected disabled>Kategori</option>
                                                    @foreach($kategori as $row)
                                                    <option value="{{ $row->id_kategori }}">{{ $row->kategori }}
                                                    </option>
                                                    @endforeach
                                                </select>
                                                <button type="submit" class="btn btn-lg btn-default">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                            </div>
                            <form method="get" action="{{route('doc.index')}}">
                                <div class="form-group">
                                    <label for="keyword" class="col-sm-2 control-label">Search</label>
                                    <div class="input-group input-group-lg">
                                        <input type="search" class="form-control form-control-lg" name="keyword"
                                            value="{{Request::get('keyword')}}" value="Lorem ipsum">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-lg btn-default">
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>


                    <!-- /.card-header -->

                    <div class="card-body">
                        @if(Request::get('keyword'))
                        <div class="alert" style="background-image: linear-gradient(to right, #a2c2d4, #7effe3);">
                            Hasil Pencarian Dokumen dengan Keyword : <b>{{ Request::get('keyword') }}</b>
                        </div>
                        @endif

                        @if(Request::get('id_kategori'))
                        <div class="alert" style="background-image: linear-gradient(to right, #a2c2d4, #7effe3);">
                            Hasil Pencarian Dokumen dengan Kategori : <b>{{ $nama_kategori }}</b>
                        </div>
                        @endif
                        @include('alert.success')
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Judul</th>
                                    <th>Tahun</th>
                                    <th>jumlah halaman</th>
                                    <th>Publisher</th>
                                    <th>Kategori</th>
                                    <th>Action</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data_dokument as $row)
                                <tr>
                                    <td>{{ $loop->iteration + ($data_dokument->perPage() * ($data_dokument->currentPage() - 1)) }}
                                    </td>
                                    <td>{{ str_limit($row->judul_dokumen , 50, ' ...') }}</td>
                                    <td>{{ $row->tahun }}</td>
                                    <td>{{ $row->jumlah_halaman }}</td>
                                    <td>{{ $row->publisher }}</td>
                                    <td>{{ $row->kategori->kategori}}</td>
                                    <td>
                                        
                                            @can("dokumen-delete")
                                           <button data-judul="{{$row->judul_dokumen}}" type="submit" class="btn btn-round btn-warning fas fa-trash-alt hapus"
                                                data-id="{{ $row->id  }}"></i></button>
                                            @endcan
                                            @can("dokumen-edit")
                                            <a class="btn btn-round btn-info btn-md far fa-edit"
                                                href="{{ route('doc.edit',[$row->id]) }}"></a>
                                            @endcan
                                            @can("preview-admin")
                                            <a href="{{route('previewdoc',[$row->id])}}"
                                                class="btn bg-gradient-success far fa-eye"></a>
                                            @endcan
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <br>
                        <tfoot>
                            <nav aria-label="Page navigation example">
                                <ul class="pagination justify-content-center">
                                    {{ $data_dokument->appends(Request::all())->links() }}
                                </ul>
                            </nav>
                        </tfoot>

                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    </div>
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->


<script>
    $(function () {
    $('#example2').DataTable({
    "paging": false,
    "lengthChange": true,
    "searching": false,
    "ordering": true,
    "info": false,
    "autoWidth": false,
    "responsive": true,
    
    });
  });
  
</script>

<script>
    $(function () {
      $('.select2').select2()
    });
</script>

@push('addon-script')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript">
    $('.hapus').click( function(){
                  var judulid = $(this).attr('data-id');
                  var judul_data = $(this).attr('data-judul');
                  swal({
                      title: "Yakin?",
                      text: "Anda akan menghapus data dengan judul  "+judul_data+"",
                      icon: "warning",
                      buttons: true,
                      dangerMode: true,
                      })
                      .then((willDelete) => {
                      if (willDelete) {
                          window.location = "/hapus/"+judulid+"" 
                          swal("Data berhasil dihapus", {
                          icon: "success",
                          });
                      } else {
                          swal("Data Tidak Jadi dihapus");
                      }
                      });
              })
                          
</script>
@endpush

@endsection