routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::middleware('example-saml-auth')->group(function () {
//     Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');
// });
// Route::redirect('about-page', 'about');

Route::middleware('example-saml-auth')->group(function () {
    Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');

});

Route::namespace('Auth')->group(function () {
    Route::post('login', 'LoginController@authenticate')->name('login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    // Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');
});

    Route::group(['middleware' => 'App\Http\Middleware\Authenticate'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/dashboardUser', 'DashboardUserController@index')->name('dashboardUser');
    Route::get('/dashboardShow-{id}', 'DashboardUserController@show')->name('dashboardShow');

    //Route::get('/dashboardUser-{id}', 'dashboardUserController@show')->name('dashboard');
    Route::get('file/download/{file}', 'kumpulanEbookController@download')->name('download');
    Route::resource('/user', 'UserController');
    Route::get('/profil', 'ProfilController@index')->name('profil.index');
    Route::post('/update-profil/{id}', 'ProfilController@update')->name('update.profil');
    Route::match(['get', 'post'], '/edit/{id}', 'KategoriController@edit');
    //Route::match(['get', 'post'], '/edit/{id}', 'sliderController@edit');
    Route::resource('/document', 'KelolaDocumentController');
    Route::get('/delete/{id}', 'KelolaDocumentController@delete')->name('delete');
    Route::get('/hapus/{id}', 'DocumentController@hapus')->name('hapus');
    Route::get('/buang/{id}', 'KategoriController@buang')->name('buang');
    Route::get('/komen/{id}', 'ForumController@komen')->name('komen');
    Route::get('/buku/{id}', 'AdminEbookController@buku')->name('buku');
    Route::get('/bukuadmin/{id}', 'EbookController@bukuadmin')->name('bukuadmin');
    Route::get('/usersdel/{id}', 'UserController@usersdel')->name('usersdel');
    Route::resource('/doc', 'DocumentController');
    Route::resource('/kategori', 'KategoriController')->except(['destroy']);;
    Route::resource('/like', 'MyLikeController');
    Route::resource('/reference', 'MyReferenceController');
    Route::resource('/forum', 'ForumController');
    Route::resource('/ebook', 'EbookController');
    Route::resource('/adminEbook', 'AdminEbookController');
    Route::resource('/kumpulanEbook', 'KumpulanEbookController');
    Route::post('/documen/{id}', 'MyReferenceController@komentar');
    Route::get('report', 'KelolaDocumentController@report')->name('report');
    Route::get('reportAdmin', 'DocumentController@report')->name('reportAdmin');
    Route::get('reportcomen', 'ForumController@reportc')->name('reportcomen');
    Route::get('export', 'UserController@export')->name('export');
    Route::get('kategoriexport', 'KategoriController@reportkategori')->name('kategoriexport');
    Route::post('import', 'UserController@importexel')->name('import');
    Route::post('importdokumen', 'UserController@importexel')->name('importdokumen');
    Route::post('importkategori', 'KategoriController@import')->name('importkategori');
    Route::post('/likedislike', 'KategoriController@likedislike')->name('likedislike');
    Route::post('/viewadd', 'MyReferenceController@addview')->name('viewadd');
    Route::post('/filter', 'KategoriController@filter')->name('filter');
    Route::get('/preview-{id}', 'PreviewController@index')->name('preview');
    Route::get('/previewdoc-{id}', 'PreviewdocController@index')->name('previewdoc');
    Route::post('/getjudul', 'MyReferenceController@getjudul');
    Route::post('/reference/{id}', 'MyReferenceController@insertData')->name('reference.insertData');
    Route::resource('/gambar', 'GambarController');
    Route::get('locale/{locale}', function ($locale) {
        \Session::put('locale', $locale);
        return redirect()->back();
    });
    });
Route::view('loginn', 'general.loginn');
    // Route::get('/', function () {
    // if( Auth::check() && Auth::user()->hasRole("pusdiklat") ) {
    //             return redirect()->intended('dashboard');
    // }
    // else {
    // return redirect()->intended('dashboardUser');
    // }
    // })->name('home');

// Route::get('/', function () {
//         return redirect('dahsboardUuser');
//     });

// Route::get('/', function () {
//     return view('general.loginn');
// })->name('home');

    

Route::get('/', function () {
    return view('general.loginn');
})->name('home');


// Route::get('/', function () {
//     return redirect('ReferenceLearning');
// })->name('home');;

// Route::view('ReferenceLearning', 'general.login');

// Route::get('/ReferenceLearning', 'LoginController@index')->name('general.login');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    protected $primaryKey = 'id';
    protected $table = 'user_auth';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'username',
        'email',
        'password',
        'full_name',
        'avatar_file',
        'user_type_id',
        'user_entity_id',
        'user_key',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password','remember_token',
        // 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function KelolaUser()
    {
        return $this->belongsTo('App\Models\KelolaUser', 'user_type_id');
    }
}

app/Models/UserType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserType extends Model
{
    protected $table = 'user_type';
    protected $primaryKey = 'id';
    protected $fillable = [
        'id',
        'type',
    ];
}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Validator;
use Illuminate\Support\Facades\Auth;
use App\Http\Resources\UserResource;
class UserController extends Controller
{
    //public $successStatus = 200;

    public function login(Request $request)
    {
        $input = $request->all();
        $validator = Validator::make($input, [
            'username' => 'required',
            'password' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'status' => FALSE,
                'msg' => $validator->errors()
            ], 400);
        }

        $username = $request->input('username');
        $password = $request->input('password');

        $user = User::where([
            ['username', $username]
        ])->first();
       

        if (is_null($user)) {
            //jika pegawai tidak ditemukan
            return response()->json([
                'status' => FALSE,
                'msg' => 'Username Tidak ditemukan'
            ], 200);
        } else {
            //jika pegawai ditemukan
            if (password_verify($password, $user->password)) {
                //jika password sesuai
                return response()->json([
                    'status' => TRUE,
                    'msg' => 'Username ditemukan',
                    'user' => new UserResource($user)
                ], 200);
            } else {
                //jika password tidak sesuai
                return response()->json([
                    'status' => FALSE,
                    'msg' => 'Username & Password Tidak Sesuai',
                ], 200);
            }
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Excel;
use Validator;
use App\Models\User;
use App\Jobs\ImportJob;
use App\Models\KelolaUser;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use App\Exports\UserExport;
use App\Imports\UserImport;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Models\Permission;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:user-list', ['only' => ['index','show']]);
        $this->middleware('permission:user-edit', ['only' => ['index','update']]);
        $this->middleware('permission:user-create', ['only' => ['create','store']]);
        $this->middleware('permission:user-delete', ['only' => ['delete']]);
        $this->middleware('permission:user-import-export', ['only' => ['export', 'importexel']]);
    }

    public function index(Request $request)
    {
        $roles = Role::get();
        $query = User::orderBy('created_at', 'desc');

        if($request->has("keyword")){
            $query->where("full_name", "like", "%$request->keyword%");
        }

        if($request->has("role")){
            $query->whereHas("roles", function($q) use ($request){
                $q->where("name", $request->role);
            });
        }

        if(!Auth::user()->hasRole("pusdiklat")){
            $query->whereHas("roles", function($q) use ($request){
                $q->where("name", '!=', "pusdiklat");
            });
        }


        $data_user = $query->paginate(10);
        return view('user.index', compact('data_user', "roles"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::get();

        return view('user.create', compact('roles'));
    }




    /* @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'full_name'    => 'required|max:250',
            'username'     => 'required|max:100|unique:user_auth',
            'email'        => 'required|email|max:255',
            'password'     => 'required|max:250',
            'role_id'   => 'required'
        ]);

        $request->merge([ 'password' => bcrypt($request['password']) ]);
        $user = User::create($request->except('_token', '_method', 'role_id', 'permission'));

        $role = Role::where("id", $request->role_id)->first();
        $user->removeRole($role->id);
        $user->assignRole($role->id);


        $permissionSuperAdmin = Permission::pluck("id", "id")->all();
        $permissionAdmin = Permission::whereIn("name", ['profile', 'ebook-list-admin', 'ebook-create-admin', 'ebook-edit-admin', 'ebook-delete-admin', 'dokumen-list', 'dokumen-create', 'dokumen-edit', 'dokumen-delete', 'reference', 'dashboard-user', 'like'])->pluck("id", "id")->all();
        $permissionUser = Permission::whereIn("name", ['profile', 'reference', 'like', 'dashboard-user', 'kumpulan-buku'])->pluck("id", "id")->all();

        $user->assignRole($role->id);

        if ($role->name == "pusdiklat") {
            $user->syncPermissions($permissionSuperAdmin);
        } elseif ($role->name == "updl") {
            $user->syncPermissions($permissionAdmin);
        } elseif ($role->name == "siswa") {
            $user->syncPermissions($permissionUser);
        }

        return redirect()->route('user.index')->with('status', 'User Berhasil Ditambahankan');
    }

    public function export()
    {
        $full_name = now();
        // dd($full_name);
         return Excel::download(new UserExport, 'user' . $full_name . '.xlsx');
    }
    public function importexel(Request $request){
        // validasi
        // $this->validate($request, [

        //     'file' => 'required|mimes:csv,xls,xlsx|max:50048'
        // ]);
        // // $Kelola = $request->all();
        // // menangkap file excel
        // if($file = $request->file('file')){
        //     $nama_file = $file->getClientOriginalName();

        //     // upload ke folder di dalam folder public
        //     $file->move('uploads', $nama_file);

        //     // import data
        //     Excel::import(new UserImport, public_path('/uploads/' . $nama_file));
        //     return redirect()->back()->with(['success' => 'Upload success']);
        // };
        // //$Kelola['password'] = bcrypt($Kelola['password']);
        // // membuat nama file unik
        // return redirect()->back()->with(['error' => 'Please choose file before']);
        $this->validate($request, [
            'file' => 'required|mimes:xls,xlsx,csv'
        ]);

        if ($request->hasFile('file')) {
            //UPLOAD FILE
            $file = $request->file('file');
            $filename = time() . '.' . $file->getClientOriginalExtension();
            $file->storeAs(
                'public',
                $filename
            );

            //MEMBUAT JOBS DENGAN MENGIRIMKAN PARAMETER FILENAME
            ImportJob::dispatch($filename);
            return redirect()->back()->with(['success' => 'Upload success']);
        }
        return redirect()->back()->with(['warning' => 'Please choose file before']);

    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Models\KelolaUser  $kelolaUser
     * @return \Illuminate\Http\Response
     */
    public function show(KelolaUser $kelolaUser)
    {
        //
    }

    /**e
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\KelolaUser  $kelolaUser
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Role::get();;
        $user =  User::findOrFail($id);
        $permission = Permission::get();
        $userRole = $user->roles->pluck("name")->toArray();
        $userPermission = $user->permissions->pluck("name")->toArray();

        //dd($userPermission, $user->getAllPermissions()->pluck("name")->toArray());
        return view('user.edit', compact('user', 'roles', 'permission', 'userRole', 'userPermission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\KelolaUser  $kelolaUser
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $data = $request->all();

        $validasi = Validator::make($data, [
            'full_name' => 'required|max:250',
            'username'  => 'required|max:100|unique:user_auth,username,' . $id,
            'email'     => 'required|email|max:255' ,
            'password'  => 'sometimes|nullable|min:6',
        ]);

        if ($validasi->fails()) {
            return redirect()->route('user.edit', [$id])->withErrors($validasi);
        }

        if ($request->input('password')) {
            //jika pasword diisi
            $data['password'] = bcrypt($data['password']);
        } else {
            //juka passowrd tydak diisi
            $data = Arr::except($data, ['password']);
        }

        $user->update($data);

        $user->removeRole($request->role_id);
        $user->assignRole($request->role_id);
        $user->syncPermissions($request->permission);

        return redirect()->route('user.index')->with('status', 'User Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\KelolaUser  $kelolaUser
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect()->route('user.index')->with('status', 'user berhasil di hapus');
    }
    public function usersdel($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect()->route('user.index')->with('status', 'user berhasil di hapus');
    }
}

resources/views/user/create.blade.php
@extends('layoutt.master-template')

@section('title')
Input User
@endsection

@section('content')

<div class="col-md-12">
    <!-- general form elements disabled -->
    <!-- /.card-header -->
    <div class="card-body">
        @include('sweetalert::alert')
        <form method="post" action="{{ route('user.store')}}" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="full_name">Nama</label>
                        <input name="full_name" id="full_name"
                            class="form-control @error('full_name') is-invalid @enderror" placeholder="masukan nama"
                            value="{{old('full_name')}}">
                        @error('full_name')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-sm-6">
                    <!-- text input -->
                    <div class="form-group ">
                        <label for="email">Email</label>
                        <input name="email" id="email" class="form-control @error('email') is-invalid @enderror"
                            placeholder="masukan email" value="{{old('email')}}">
                        @error('email')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <!-- text input -->
                    <div class="form-group ">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password"
                            class="form-control @error('password') is-invalid @enderror" placeholder="masukan Password"
                            value="{{old('password')}}">
                        @error('password')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>

                </div>
                <div class="col-sm-4">
                    <!-- text input -->
                    <div class="form-group ">
                        <label for="username">username</label>
                        <input name="username" id="username"
                            class="form-control @error('username') is-invalid @enderror" placeholder="masukan username"
                            value="{{old('username')}}">
                        @error('username')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>

                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="user_type_id">Level</label>
                        <select id="role_id" name="role_id" class="form-control">
                            @foreach($roles as $row )
                           <option value="{{ $row->id }}">
                                {{ $row->name }}
                            </option>
                            @endforeach
                        </select>
                        @error('role_id')
                            <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                    <!-- text input -->
                </div>

            </div>


            <div class="form-group">
                <a href="{{route('user.index')}}" class="btn btn-warning btn-xl "><span class="fas fa-backward"></span>
                    Kembali</a>
                <button type="submit" class="btn btn-success btn-xl"><i class="far fa-save"></i> Simpan</button>

            </div>
        </form>

    </div>

</div>


@endsection

resources/views/user/edit.blade.php
@extends('layoutt.master-template')

@section('title')
Edit User
@endsection

@section('content')

<div class="col-md-12">
    <!-- general form elements disabled -->
    <!-- /.card-header -->
    <div class="card-body">
        @if($errors->any())
        <ul class="alert alert-danger">
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        @endif
        <form class="form-horizontal" method="post" action="{{ route('user.update',[$user->id]) }}"
            enctype="multipart/form-data">
            @csrf
            {{ method_field('PUT') }}
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="full_name">Nama</label>
                        <input name="full_name" id="full_name" class="form-control" placeholder="masukan nama"
                            value="{{$user->full_name}}">
                    </div>
                </div>
                <div class="col-sm-6">
                    <!-- text input -->
                    <div class="form-group ">
                        <label for="email">Email </label>
                        <input name="email" id="email" class="form-control" placeholder="masukan email"
                            value="{{$user->email}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <!-- text input -->
                    <div class="form-group ">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password" class="form-control"
                            placeholder="masukan Password" >
                    </div>

                </div>
                <div class="col-sm-4">
                    <!-- text input -->
                    <div class="form-group ">
                        <label for="username">username</label>
                        <input name="username" id="username" class="form-control" placeholder="masukan username"
                            value="{{$user->username}}">
                    </div>

                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="role_id">Level</label>
                        <div class="input-group">
                        <select id="role_id" name="role_id" class="form-control">
                            @foreach($roles as $row )
                                <option value="{{ $row->name }}" {{ in_array($row->name, $userRole ) ? "selected" : '' }}>
                                    {{ $row->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <!-- text input -->
                </div>
            </div>
        <div class="col-md-12">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Setting Hak Akses</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        @foreach($permission as $value)
                        <div class="col-md-3">
                            <div class="checkbox-single">
                                <label>
                                    {{ Form::checkbox('permission[]', $value->id, in_array($value->name, $userPermission) ? true : false, array('class' => 'name')) }}
                                    {{ $value->name }}
                                </label>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
            <div class="form-group">
                <a href="{{route('user.index')}}" class="btn btn-warning btn-xl"><span class="fas fa-backward"></span> Kembali</a>
                <button type="submit" class="btn btn-success btn-xl"><span class="fas fa-pen-square"></span> Simpan</button>

            </div>
        </form>

    </div>

</div>


@endsection