routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Route::middleware('example-saml-auth')->group(function () {
//     Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');
// });
// Route::redirect('about-page', 'about');

Route::middleware('example-saml-auth')->group(function () {
    Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');

});

Route::namespace('Auth')->group(function () {
    Route::post('login', 'LoginController@authenticate')->name('login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    // Route::name('logout')->post('logout', '\Aacotroneo\Saml2\Http\Controllers\Saml2Controller@logout');
});

    Route::group(['middleware' => 'App\Http\Middleware\Authenticate'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/dashboardUser', 'DashboardUserController@index')->name('dashboardUser');
    Route::get('/dashboardShow-{id}', 'DashboardUserController@show')->name('dashboardShow');

    //Route::get('/dashboardUser-{id}', 'dashboardUserController@show')->name('dashboard');
    Route::get('file/download/{file}', 'kumpulanEbookController@download')->name('download');
    Route::resource('/user', 'UserController');
    Route::get('/profil', 'ProfilController@index')->name('profil.index');
    Route::post('/update-profil/{id}', 'ProfilController@update')->name('update.profil');
    Route::match(['get', 'post'], '/edit/{id}', 'KategoriController@edit');
    //Route::match(['get', 'post'], '/edit/{id}', 'sliderController@edit');
    Route::resource('/document', 'KelolaDocumentController');
    Route::get('/delete/{id}', 'KelolaDocumentController@delete')->name('delete');
    Route::get('/hapus/{id}', 'DocumentController@hapus')->name('hapus');
    Route::get('/buang/{id}', 'KategoriController@buang')->name('buang');
    Route::get('/komen/{id}', 'ForumController@komen')->name('komen');
    Route::get('/buku/{id}', 'AdminEbookController@buku')->name('buku');
    Route::get('/bukuadmin/{id}', 'EbookController@bukuadmin')->name('bukuadmin');
    Route::get('/usersdel/{id}', 'UserController@usersdel')->name('usersdel');
    Route::resource('/doc', 'DocumentController');
    Route::resource('/kategori', 'KategoriController')->except(['destroy']);;
    Route::resource('/like', 'MyLikeController');
    Route::resource('/reference', 'MyReferenceController');
    Route::resource('/forum', 'ForumController');
    Route::resource('/ebook', 'EbookController');
    Route::resource('/adminEbook', 'AdminEbookController');
    Route::resource('/kumpulanEbook', 'KumpulanEbookController');
    Route::post('/documen/{id}', 'MyReferenceController@komentar');
    Route::get('report', 'KelolaDocumentController@report')->name('report');
    Route::get('reportAdmin', 'DocumentController@report')->name('reportAdmin');
    Route::get('reportcomen', 'ForumController@reportc')->name('reportcomen');
    Route::get('export', 'UserController@export')->name('export');
    Route::get('kategoriexport', 'KategoriController@reportkategori')->name('kategoriexport');
    Route::post('import', 'UserController@importexel')->name('import');
    Route::post('importdokumen', 'UserController@importexel')->name('importdokumen');
    Route::post('importkategori', 'KategoriController@import')->name('importkategori');
    Route::post('/likedislike', 'KategoriController@likedislike')->name('likedislike');
    Route::post('/viewadd', 'MyReferenceController@addview')->name('viewadd');
    Route::post('/filter', 'KategoriController@filter')->name('filter');
    Route::get('/preview-{id}', 'PreviewController@index')->name('preview');
    Route::get('/previewdoc-{id}', 'PreviewdocController@index')->name('previewdoc');
    Route::post('/getjudul', 'MyReferenceController@getjudul');
    Route::post('/reference/{id}', 'MyReferenceController@insertData')->name('reference.insertData');
    Route::resource('/gambar', 'GambarController');
    Route::get('locale/{locale}', function ($locale) {
        \Session::put('locale', $locale);
        return redirect()->back();
    });
    });
Route::view('loginn', 'general.loginn');
    // Route::get('/', function () {
    // if( Auth::check() && Auth::user()->hasRole("pusdiklat") ) {
    //             return redirect()->intended('dashboard');
    // }
    // else {
    // return redirect()->intended('dashboardUser');
    // }
    // })->name('home');

// Route::get('/', function () {
//         return redirect('dahsboardUuser');
//     });

// Route::get('/', function () {
//     return view('general.loginn');
// })->name('home');

    

Route::get('/', function () {
    return view('general.loginn');
})->name('home');


// Route::get('/', function () {
//     return redirect('ReferenceLearning');
// })->name('home');;

// Route::view('ReferenceLearning', 'general.login');

// Route::get('/ReferenceLearning', 'LoginController@index')->name('general.login');

resources/views/layoutt/header.blade.php
<style>
    .gradient3 {
        background-image: linear-gradient(to right, #004d78, #7effe3);
    }

    .tulisan {
        color: antiquewhite;
    }

    .bold {
        font-weight: bold;
    }

    .sticky-header {
        width: 100%;
        position: fixed;

    }
</style>
<nav class="gradient3 main-header navbar navbar-expand-md navbar-light navbar-white sticky-header">
    {{-- <div class="container"> --}}
    <a style="margin-left: 25px !important;" href="{{route('dashboard')}}" class="navbar-brand">
        <img src="{{asset('image/logo.png')}}" alt="logo pln" class="brand-image elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light tulisan" style="font-weight: 600 !important;font-family:'Inter' !important;">Reference Learning</span>
    </a>
    <!-- Right navbar links -->
    <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i class="fas fa-bars"></i>
                <b>Menu</b></a>
        </li>
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown no-arrow show">
        </li>
        <li style="margin-left: 20px; margin-right:10px;" class="nav-item dropdown user user-menu">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                @if(Auth::user()->avatar_file != NULL)
                <img src="{{ URL::to('/') }}/uploads/document/{{Auth :: user()->avatar_file}}"
                    class="user-image img-circle elevation-2 alt=" User Image">
                @elseif(Auth::user()->avatar_file == NULL)
                <img src="{{ asset('assets/img/avatar.png') }}" class="user-image img-circle elevation-2 alt=" User
                    Image">
                @endif
                <i class="hidden-xs dropdown-toggle"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in show"
                    aria-labelledby="userDropdown">
                    <a class="dropdown-item">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        {{Auth :: user()->full_name}}
                    </a>
                    <a class="dropdown-item" href="{{route('profil.index') }}">
                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                        Setting Profil
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{route('logout')}}">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Keluar
                    </a>
                </div>
                <!-- User image -->
            </ul>
        </li>


    </ul>
    {{-- <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Dropdown
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                @if(app()->getLocale()=='en')
                <a href="{{url('locale/id')}}" class="dropdown-item">@lang('indonesian')</a>
    @endif
    @if(app()->getLocale()=='id')
    <a href="{{url('locale/en')}}" class="dropdown-item">@lang('english')</a>
    @endif

    </div>
    </div> --}}

</nav>

resources/views/layoutt/more.blade.php
<!-- start: Javascript -->
<script src="{{ asset('miminium-master/asset/js/jquery.min.js')}}"></script>
<script src="{{ asset('miminium-master/asset/js/jquery.ui.min.js')}}"></script>
<script src="{{ asset('miminium-master/asset/js/bootstrap.min.js')}}"></script>



<!-- plugins -->
<script src="{{ asset('miminium-master/asset/js/plugins/moment.min.js')}}"></script>
<script src="{{ asset('miminium-master/asset/js/plugins/jquery.datatables.min.js')}}"></script>
<script src="{{ asset('miminium-master/asset/js/plugins/datatables.bootstrap.min.js')}}"></script>
<script src="{{ asset('miminium-master/asset/js/plugins/jquery.nicescroll.js')}}"></script>
<script src="{{ asset('miminium-master/asset/js/plugins/bootstrap-material-datetimepicker.js')}}"></script>

<script src="{{ asset('miminium-master/asset/js/main.js')}}"></script>

resources/views/layoutt/sidebar.blade.php
<style>
    .sticky-sidebar {
        position: fixed;

    }

    .text-sidebar {
        font-weight: 500;
        font-family: 'Poppins';
        font-size: 17px;
    }
</style>

<aside class="main-sidebar control-sidebar sidebar-light-primary elevation-4" style="overflow-x :hidden;">
    <!-- Brand Logo -->
    <a href="{{asset('admin/index3.html')}}" class="brand-link">
        <img src="{{asset('image/logo.jpg')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light"></span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar sticky-sidebar ">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            {{-- <div class="image">
                <img src="{{asset('image/user.png')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="#" class="d-block">{{Auth::user()->full_name}}</a>
        </div> --}}
    </div>
    <hr>
    <!-- Sidebar Menu -->
    <nav class="mt-2">
        @role("pusdiklat")
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
            <li class="nav-item">
                <a href="{{route('dashboard')}}" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p class="text-sidebar">
                        Dashboard
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('profil.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-address-card"></i>
                    <p class="text-sidebar">
                        Kelola profil
                    </p>
                </a>
            </li>

            <li class="nav-item">
                {{-- <a href="{{ route('kategori', ['id' => '1']) }}" class="nav-link"> --}}
                <a href="{{ route('kategori.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-random"></i>
                    <p class="text-sidebar">
                        Kategori
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{route('forum.index')}}" class="nav-link">
                    <i class="nav-icon fas fa-chalkboard-teacher"></i>
                    <p class="text-sidebar">
                        Kelola Komentar
                    </p>
                </a>
            </li>
            {{-- <li class="nav-item">
                        <a href="{{route('like.index')}}" class="nav-link">
            <i class="nav-icon fab fa-gratipay"></i>
            <p>
                Like
            </p>
            </a>
            </li> --}}
            <li class="nav-item">
                <a href="{{route('document.index')}}" class="nav-link">
                    <i class="nav-icon fas fa-file-alt"></i>
                    <p class="text-sidebar">
                        Kelola Dokumen
                    </p>
                </a>
            </li>
            {{-- <li class="nav-item">
                        <a href="{{ route('document.index') }}" class="nav-link">
            <i class="fas fa-file-alt"></i>
            <p>
                kelola-document
            </p>
            </a>
            </li> --}}
            <li class="nav-item">
                <a href="{{ route('ebook.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-book"></i>
                    <p class="text-sidebar">
                        Kelola Buku
                    </p>
                </a>
            </li>
            {{-- <li class="nav-item">
                <a href="{{ route('gambar.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-images"></i>
                    <p class="text-sidebar">
                        Slider Login
                    </p>
                </a>
            </li> --}}
            <li class="nav-item">
                <a href="{{ route('user.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-users-cog"></i>
                    <p class="text-sidebar">
                        Kelola User
                    </p>
                </a>
            </li>
        </ul>
        @endrole
        @role("updl")
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                            with font-awesome or any other icon font library -->
            <li class="nav-item">
                <a href="{{route('dashboardUser')}}" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p class="text-sidebar">
                        Dashboard
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{route('profil.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-address-card"></i>
                    <p class="text-sidebar">
                        Kelola profil
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{route('reference.index')}}" class="nav-link">
                    <i class="nav-icon fas fa-chalkboard-teacher"></i>
                    <p class="text-sidebar">
                        Reference
                    </p>
                </a>
            </li>

            <li class="nav-item">
                <a href="{{route('doc.index')}}" class="nav-link">
                    <i class="nav-icon fas fa-file-alt"></i>
                    <p class="text-sidebar">
                        Kelola Dokumen
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('adminEbook.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-book"></i>
                    <p class="text-sidebar">
                        Kelola Buku
                    </p>
                </a>
            </li>
            @can("kategori-list")
            <li class="nav-item">
                {{-- <a href="{{ route('kategori', ['id' => '1']) }}" class="nav-link"> --}}
                <a href="{{ route('kategori.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-random"></i>
                    <p class="text-sidebar">
                        Kategori
                    </p>
                </a>
            </li>
            @endcan
            @can("user-list")
            <li class="nav-item">
                <a href="{{ route('user.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-users-cog"></i>
                    <p class="text-sidebar">
                        Kelola User
                    </p>
                </a>
            </li>
            @endcan
            @can("komentar-list")
            <li class="nav-item">
                <a href="{{route('forum.index')}}" class="nav-link">
                    <i class="nav-icon fas fa-chalkboard-teacher"></i>
                    <p class="text-sidebar">
                        Kelola Komentar
                    </p>
                </a>
            </li>
            @endcan
            @can("kumpulan-buku")
            <li class="nav-item">
                <a href="{{ route('kumpulanEbook.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-users-cog"></i>
                    <p class="text-sidebar">
                        Kumpulan Buku
                    </p>
                </a>
            </li>
            @endcan
            @can("ebook-list-superadmin")
            <li class="nav-item">
                <a href="{{ route('ebook.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-book"></i>
                    <p class="text-sidebar">
                        Kelola Buku Super Admin
                    </p>
                </a>
            </li>
            @endcan
            {{-- <li class="nav-item">
                                    <a href="{{ route('document.index') }}" class="nav-link">
            <i class="fas fa-file-alt"></i>
            <p>
                kelola-document
            </p>
            </a>
            </li> --}}

        </ul>
        @endrole
        @role("siswa")
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                            with font-awesome or any other icon font library -->
            <li class="nav-item">
                <a href="{{route('dashboardUser')}}" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p class="text-sidebar">
                        Dashboard
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('profil.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-address-card"></i>
                    <p class="text-sidebar">
                        Kelola profil
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{route('reference.index')}}" class="nav-link">
                    <i class="nav-icon fas fa-chalkboard-teacher"></i>
                    <p class="text-sidebar">
                        Reference
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{route('like.index')}}" class="nav-link">
                    <i class="nav-icon fab fa-gratipay"></i>
                    <p class="text-sidebar">
                        Like
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('kumpulanEbook.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-users-cog"></i>
                    <p class="text-sidebar">
                        Kumpulan Buku
                    </p>
                </a>
            </li>

            @can("dokumen-list")
            <li class="nav-item">
                <a href="{{route('doc.index')}}" class="nav-link">
                    <i class="nav-icon fas fa-file-alt"></i>
                    <p class="text-sidebar">
                        Kelola Dokumen
                    </p>
                </a>
            </li>
            @endcan
            @can("ebook-list-admin")
            <li class="nav-item">
                <a href="{{ route('adminEbook.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-book"></i>
                    <p class="text-sidebar">
                        Kelola Buku Admin
                    </p>
                </a>
            </li>
            @endcan
            @can("kategori-list")
            <li class="nav-item">
                {{-- <a href="{{ route('kategori', ['id' => '1']) }}" class="nav-link"> --}}
                <a href="{{ route('kategori.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-random"></i>
                    <p class="text-sidebar">
                        Kategori
                    </p>
                </a>
            </li>
            @endcan
            @can("komentar-list")
            <li class="nav-item">
                <a href="{{route('forum.index')}}" class="nav-link">
                    <i class="nav-icon fas fa-chalkboard-teacher"></i>
                    <p class="text-sidebar">
                        Kelola Komentar
                    </p>
                </a>
            </li>
            @endcan
            @can("ebook-list-superadmin")
            <li class="nav-item">
                <a href="{{ route('ebook.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-book"></i>
                    <p class="text-sidebar">
                        Kelola Buku Super Admin
                    </p>
                </a>
            </li>
            @endcan
        </ul>
        @endrole
    </nav>
    <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>